name: Build Vulkan-Guide PDF

on:
  workflow_dispatch:   # 仅手动触发，避免自动跑

jobs:
  pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true   # 拉取 UI bundle

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Antora & PDF extension
        run: |
          npm i -g @antora/cli @antora/site-generator-default @antora/pdf-extension

      - name: Build HTML + PDF
        run: |
          # 用官方 playbook，只额外加 PDF 输出
          cp antora-playbook.yml antora-pdf-playbook.yml
          cat <<EOF >> antora-pdf-playbook.yml
          output:
            destinations:
            - provider: fs
              path: build/site
            - provider: pdf
              path: build/vulkan-guide.pdf
              page_break_level: 1
              pdf_style: khronos
          EOF
          antora antora-pdf-playbook.yml

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Vulkan-Guide-PDF
          path: build/vulkan-guide.pdf
