# Copyright 2021 The Khronos Group, Inc.
# SPDX-License-Identifier: Apache-2.0
name: PDF

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
   antora-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can
      # access it
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install Antora CLI and site generator
      - name: Install Antora
        run: npm i -g @antora/cli@3.1 @antora/site-generator@3.1

      # Setup Antora directory structure
      - name: Setup Antora directory structure
        run: |
          make -f antora/Makefile setup

      # Create a simple Antora playbook
      - name: Create Antora playbook
        run: |
          echo "site:
            title: Vulkan Guide
            url: https://github.com/KhronosGroup/Vulkan-Guide
            start_page: guide::index.adoc
          content:
            sources:
            - url: .
              start_path: antora
          ui:
            bundle:
              url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
              snapshot: true" > antora-playbook.yml

      # 新增：装 Ruby 工具链
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install asciidoctor-pdf
        run: |
          gem install asciidoctor-pdf
          
      - name: Install Antora + PDF extension (local)
        run: |
          npm i --save-dev @antora/cli@3.1 @antora/site-generator@3.1 @antora/pdf-extension

      - name: Create Antora playbook with PDF
        run: |
          cat > antora-playbook.yml <<'EOF'
          site:
            title: Vulkan Guide
            start_page: guide::index.adoc
          content:
            sources:
            - url: .
              start_path: antora
          ui:
            bundle:
              url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
              snapshot: true
          antora:
            extensions:
            - require: '@antora/pdf-extension'
          output:
            destinations:
            - provider: fs
              path: build/site
            - provider: pdf
              path: build/vulkan-guide.pdf
              page_break_level: 1
              pdf_style: khronos
          EOF

      - name: Build Antora site & PDF
        run: npx antora --stacktrace antora-playbook.yml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vulkan-guide-pdf
          path: build/vulkan-guide.pdf
