# Copyright 2021 The Khronos Group, Inc.
# SPDX-License-Identifier: Apache-2.0
name: PDF

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  antora-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 1. 额外装 PDF 扩展
      - name: Install Antora + PDF extension
        run: |
          npm i -g @antora/cli@3.1 @antora/site-generator@3.1 @antora/pdf-extension

      - name: Setup Antora directory structure
        run: make -f antora/Makefile setup

      # 2. 生成含 PDF 输出的 playbook
      - name: Create Antora playbook
        run: |
          cat > antora-playbook.yml <<'EOF'
          site:
            title: Vulkan Guide
            url: https://github.com/KhronosGroup/Vulkan-Guide
            start_page: guide::index.adoc
          content:
            sources:
            - url: .
              start_path: antora
          ui:
            bundle:
              url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
              snapshot: true
          output:
            destinations:
            - provider: fs
              path: build/site        # 原有 HTML
            - provider: pdf           # 新增 PDF
              path: build/vulkan-guide.pdf
              page_break_level: 1
              pdf_style: khronos
          EOF

      - name: Build Antora site & PDF
        run: |
          OUTPUT=$(antora --stacktrace antora-playbook.yml 2>&1)
          EXIT_CODE=$?
          echo "$OUTPUT"
          if [[ "$OUTPUT" == *"ERROR"* || "$OUTPUT" == *"WARN"* ]]; then
            echo "::error::Antora build produced errors or warnings."
            exit 1
          fi
          exit $EXIT_CODE

      # 3. 同时上传 HTML 与 PDF
      - name: Archive Antora site
        uses: actions/upload-artifact@v4
        with:
          name: antora-site
          path: build/site

      - name: Archive PDF
        uses: actions/upload-artifact@v4
        with:
          name: vulkan-guide-pdf
          path: build/vulkan-guide.pdf
