name: Build PDF

on:
  workflow_dispatch:   # 手动触发
  push:
    branches: [ main ]

jobs:
  pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true   # Vulkan-Guide 引用了外部模块
          fetch-depth: 0

      - name: Install pandoc & tex
        run: |
          sudo apt-get update -y
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended \
               texlive-latex-extra texlive-xetex fonts-liberation pandoc

      - name: Merge all markdown into single file
        run: |
          find . -type f -name '*.md' | grep -v node_modules | sort > md.list
          pandoc -f markdown -t latex --pdf-engine=xelatex \
                 --toc -N --top-level-division=chapter \
                 -V geometry:margin=2.5cm -V mainfont=LiberationSerif \
                 -o Vulkan-Guide.pdf $(cat md.list)

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Vulkan-Guide
          path: Vulkan-Guide.pdf

      - name: Release  # 可选：直接发一个 Release，方便直链下载
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          tag_name: pdf-${{ github.run_number }}
          files: Vulkan-Guide.pdf
